import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Button } from "./Button";
import { ReactTable } from "./ReactTable";
import { Input } from "./Input";
import { TextArea } from "./TextArea";
import { Switch } from "./Switch";
import { SelectBox } from "./SelectBox";
export { Img, Text, Heading, Button, ReactTable, Input, TextArea, Switch, SelectBox };
